export const plans2 = [
    {
        id:'plan1',
        plan:'CLASSIC',
        price:'1400',
        benefits: [
        {plan: 'Outpatient Care', status: 'fa fa-check-circle text-success'},
        {plan: 'Hospital Admission', status:'fa fa-check-circle text-success'},
        {plan: 'Specialist Consultation', status : 'fa fa-check-circle text-success'},
        {plan: 'Advanced Lab Tests', status : 'fa fa-check-circle text-success'},
        {plan: 'Accident & Emergency', status : 'fa fa-check-circle text-success'},
        {plan: 'Neonatal & Paediatric Care', status : 'fa fa-check-circle text-success'},
        {plan: 'Management of Diabetes', status : 'fa fa-times-circle text-danger'},
        {plan: 'Dental Care', status: 'fa fa-times-circle text-danger'},
        {plan: 'Physiotherapy', status : 'fa fa-check-circle text-success'},
        {plan: 'Mental Health', status : 'fa fa-times-circle text-danger'},
        {plan: 'Major Surgeries', status : 'fa fa-times-circle text-danger'},
        {plan: 'Minor Surgeries', status : 'fa fa-check-circle text-success'},
        {plan: 'Obstetrics & Gynecology', status : 'fa fa-check-circle text-success'},
        {plan: 'Antenatal', status : 'fa fa-check-circle text-success'},
        {plan: 'Annual Health check-circles', status: 'fa fa-times-circle text-danger'},
        {plan: 'Cancer Screening*', status : 'fa fa-times-circle text-danger'},
        {plan: 'Drug Delivery & Pickup', status : 'fa fa-times-circle text-danger'},
        {plan: 'Personal Health Equipment', status : 'fa fa-times-circle text-danger'},
        {plan: 'Delivery Abroad', status : 'fa fa-times-circle text-danger'}
        ]
    },
    {
        id:'plan2',
        plan:'GOLD',
        price:'2000',
        benefits: [
        {plan: 'Outpatient Care', status: 'fa fa-check-circle text-success'},
        {plan: 'Hospital Admission', status:'fa fa-check-circle text-success'},
        {plan: 'Specialist Consultation', status : 'fa fa-check-circle text-success'},
        {plan: 'Advanced Lab Tests', status : 'fa fa-check-circle text-success'},
        {plan: 'Accident & Emergency', status : 'fa fa-check-circle text-success'},
        {plan: 'Neonatal & Paediatric Care', status : 'fa fa-check-circle text-success'},
        {plan: 'Management of Diabetes', status : 'fa fa-check-circle text-success'},
        {plan: 'Dental Care', status: 'fa fa-check-circle text-success'},
        {plan: 'Physiotherapy', status : 'fa fa-check-circle text-success'},
        {plan: 'Mental Health', status : 'fa fa-check-circle text-success'},
        {plan: 'Major Surgeries', status : 'fa fa-check-circle text-success'},
        {plan: 'Minor Surgeries', status : 'fa fa-check-circle text-success'},
        {plan: 'Obstetrics & Gynecology', status : 'fa fa-check-circle text-success'},
        {plan: 'Antenatal', status : 'fa fa-check-circle text-success'},
        {plan: 'Annual Health check-circles', status: 'fa fa-check-circle text-success'},
        {plan: 'Cancer Screening*', status : 'fa fa-times-circle text-danger'},
        {plan: 'Drug Delivery & Pickup', status : 'fa fa-check-circle text-success'},
        {plan: 'Personal Health Equipment', status : 'fa fa-times-circle text-danger'},
        {plan: 'Delivery Abroad', status : 'fa fa-times-circle text-danger'}
        ]
    },
    {
        id:'plan3',
        plan:'DIAMOND',
        price:'3000',
        benefits: [
        {plan: 'Outpatient Care', status: 'fa fa-check-circle text-success'},
        {plan: 'Hospital Admission', status:'fa fa-check-circle text-success'},
        {plan: 'Specialist Consultation', status : 'fa fa-check-circle text-success'},
        {plan: 'Advanced Lab Tests', status : 'fa fa-check-circle text-success'},
        {plan: 'Accident & Emergency', status : 'fa fa-check-circle text-success'},
        {plan: 'Neonatal & Paediatric Care', status : 'fa fa-check-circle text-success'},
        {plan: 'Management of Diabetes', status : 'fa fa-check-circle text-success'},
        {plan: 'Dental Care', status: 'fa fa-check-circle text-success'},
        {plan: 'Physiotherapy', status : 'fa fa-check-circle text-success'},
        {plan: 'Mental Health', status : 'fa fa-check-circle text-success'},
        {plan: 'Major Surgeries', status : 'fa fa-check-circle text-success'},
        {plan: 'Minor Surgeries', status : 'fa fa-check-circle text-success'},
        {plan: 'Obstetrics & Gynecology', status : 'fa fa-check-circle text-success'},
        {plan: 'Antenatal', status : 'fa fa-check-circle text-success'},
        {plan: 'Annual Health check-circles', status: 'fa fa-check-circle text-success'},
        {plan: 'Cancer Screening*', status : 'fa fa-check-circle text-success'},
        {plan: 'Drug Delivery & Pickup', status : 'fa fa-check-circle text-success'},
        {plan: 'Personal Health Equipment', status : 'fa fa-times-circle text-danger'},
        {plan: 'Delivery Abroad', status : 'fa fa-check-circle text-success'}
        ]
    },
    {
        id:'plan4',
        plan:'DIAMOND+',
        price: '5000',
        benefits: [
        {plan: 'Outpatient Care', status: 'fa fa-check-circle text-success'},
        {plan: 'Hospital Admission', status:'fa fa-check-circle text-success'},
        {plan: 'Specialist Consultation', status : 'fa fa-check-circle text-success'},
        {plan: 'Advanced Lab Tests', status : 'fa fa-check-circle text-success'},
        {plan: 'Accident & Emergency', status : 'fa fa-check-circle text-success'},
        {plan: 'Neonatal & Paediatric Care', status : 'fa fa-check-circle text-successfa fa-check-circle text-success'},
        {plan: 'Management of Diabetes', status : 'fa fa-check-circle text-success'},
        {plan: 'Dental Care', status: 'fa fa-check-circle text-success'},
        {plan: 'Physiotherapy', status : 'fa fa-check-circle text-success'},
        {plan: 'Mental Health', status : 'fa fa-check-circle text-success'},
        {plan: 'Major Surgeries', status : 'fa fa-check-circle text-success'},
        {plan: 'Minor Surgeries', status : 'fa fa-check-circle text-success'},
        {plan: 'Obstetrics & Gynecology', status : 'fa fa-check-circle text-success'},
        {plan: 'Antenatal', status : 'fa fa-check-circle text-success'},
        {plan: 'Annual Health check-circles', status: 'fa fa-check-circle text-success'},
        {plan: 'Cancer Screening*', status : 'fa fa-check-circle text-success'},
        {plan: 'Drug Delivery & Pickup', status : 'fa fa-check-circle text-success'},
        {plan: 'Personal Health Equipment', status : 'fa fa-check-circle text-success'},
        {plan: 'Delivery Abroad', status : 'fa fa-check-circle text-success'}
        ]
    }
]