export default [
    {
        id:0,
        brand:'ndlea',
        image:'assets/images/partners/ndlea.png',
    },{
        id:1,
        brand:'niepa',
        image:'assets/images/partners/niepa.jpeg',
    },{
        id:2,
        brand:'nrc',
        image:'assets/images/partners/nrc.jpeg',
    },{
        id:3,
        brand:'body of benchers',
        image:'assets/images/partners/bodyofbenchers.jpeg',
    },{
        id:4,
        brand:'fedekowe',
        image:'assets/images/partners/fedekowe.jpeg',
    },{
        id:5,
        brand:'ministry of defence',
        image:'assets/images/partners/minofdef.png',
    },{
        id:6,
        brand:'ministry of agric',
        image:'assets/images/partners/nigagric.jpeg',
    },{
        id:7,
        brand:'feduniotuoke',
        image:'assets/images/partners/feduniotuoke.png',
    },{
        id:8,
        brand:'seamhealth',
        image:'assets/images/partners/seamhealth.jpeg',
    },{
        id:9,
        brand:'Association-of-Nigerian-Women-Business-Network-ANWBN',
        image:'assets/images/partners/Association-of-Nigerian-Women-Business-Network-ANWBN.jpg',
    },{
        id:10,
        brand:'choiceclouds-logo-blue-text',
        image:'assets/images/partners/choiceclouds-logo-blue-text.png',
    },{
        id:11,
        brand:'County_finance_Logo',
        image:'assets/images/partners/County_finance_Logo.png',
    },{
        id:12,
        brand:'DeepCover',
        image:'assets/images/partners/DeepCover.png',
    },{
        id:13,
        brand:'FastCubic',
        image:'assets/images/partners/FastCubic.png',
    },{
        id:14,
        brand:'FederalUHSOtukpo',
        image:'assets/images/partners/FederalUHSOtukpo.jpg',
    },{
        id:15,
        brand:'FHIS',
        image:'assets/images/partners/FHIS.png',
    },{
        id:16,
        brand:'FMCKeffi',
        image:'assets/images/partners/FMCKeffi.png',
    },{
        id:17,
        brand:'fUAZ',
        image:'assets/images/partners/fUAZ.png',
    },{
        id:18,
        brand:'FUD',
        image:'assets/images/partners/FUD.png',
    },{
        id:19,
        brand:'GADOL-LOGO',
        image:'assets/images/partners/GADOL-LOGO.png',
    },{
        id:20,
        brand:'IHVNLOGO',
        image:'assets/images/partners/IHVNLOGO.png',
    },{
        id:21,
        brand:'Latins',
        image:'assets/images/partners/Latins.jpg',
    },{
        id:22,
        brand:'LFMP_Logo',
        image:'assets/images/partners/LFMP_Logo.png',
    },{
        id:23,
        brand:'logo2',
        image:'assets/images/partners/logo2.png',
    },{
        id:24,
        brand:'Ministry of Interior',
        image:'assets/images/partners/MinistryofInterior.png',
    },{
        id:25,
        brand:'Oau_logo',
        image:'assets/images/partners/Oau_logo.png',
    },{
        id:26,
        brand:'Uni Agric Zuru',
        image:'assets/images/partners/UniAgricZuru.png',
    },{
        id:27,
        brand:'uniben',
        image:'assets/images/partners/uniben-logo1.png',
    },
]